# This is a basic workflow to help you get started with Actions

name: Upload a Build Artifact
echo Add other actions to build


# Controls when the workflow will run
on:
  # s
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 1.0
  
